abstract class Account_settingState {}
class InitialAccount_settingState extends Account_settingState{}
class LoadingAccount_settingState extends Account_settingState{}
class SuccessAccount_settingState extends Account_settingState{}
class ErrorAccount_settingState extends Account_settingState{}